[font]
normal = { family = "Unifont", style = "Regular" }

bold = { family = "Unifont", style = "Bold" }

italic = { family = "Unifont", style = "Italic" }

# Point size of the font
size = 12.0

# Glyph offset (in pixels) for the font
offset = { x = 0, y = 0 }

[colors.primary]
background = "#000000"
foreground = "#00ff00"
